pause_print:
  target:
    device:
      integration: prusa_connect

resume_print:
  target:
    device:
      integration: prusa_connect

stop_print:
  target:
    device:
      integration: prusa_connect

set_ready:
  target:
    device:
      integration: prusa_connect

cancel_ready:
  target:
    device:
      integration: prusa_connect

start_print:
  target:
    device:
      integration: prusa_connect
  fields:
    path:
      required: true
      example: /usb/BENCHY~1.BGC
      selector:
        text:

respond_to_dialog:
  target:
    device:
      integration: prusa_connect
  fields:
    dialog_id:
      required: true
      example: 1
      selector:
        number:
          mode: box
          min: 0
    button:
      required: true
      example: YES
      selector:
        text:
